# Generated by Django 6.1.1 on 2026-09-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='marks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
