# Generated by Django 6.1.1 on 2026-09-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.IntegerField(),
        ),
    ]
