# Generated by Django 6.1.1 on 2026-09-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0002_alter_academicsession_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
